import Head from "next/head";
import React, { useState } from 'react';
import Ver1 from '../components/ver1';
import Ver2 from '../components/ver2';

export default function Home() {
  const [selectedVersion, setSelectedVersion] = useState(null);

  const renderContent = () => {
    if (selectedVersion === 'ver1') {
      return <Ver1 />;
    } else if (selectedVersion === 'ver2') {
      return <Ver2 />;
    }
    return <div>Select a version to display.</div>;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main style={{ display: 'flex', height: '100vh', width: '100vw' }}>
        <div style={{ padding: '20px', borderRight: '1px solid #eee', display: 'flex', flexDirection: 'column', gap: '10px' }}>
          <button 
            onClick={() => setSelectedVersion('ver1')} 
            style={{ 
              padding: '10px 15px', 
              fontSize: '16px', 
              cursor: 'pointer', 
              backgroundColor: selectedVersion === 'ver1' ? '#0070f3' : '#f0f0f0', 
              color: selectedVersion === 'ver1' ? 'white' : 'black',
              border: 'none',
              borderRadius: '5px',
              width: '100px'
            }}
          >
            Ver1
          </button>
          <button 
            onClick={() => setSelectedVersion('ver2')} 
            style={{ 
              padding: '10px 15px', 
              fontSize: '16px', 
              cursor: 'pointer', 
              backgroundColor: selectedVersion === 'ver2' ? '#0070f3' : '#f0f0f0', 
              color: selectedVersion === 'ver2' ? 'white' : 'black',
              border: 'none',
              borderRadius: '5px',
              width: '100px'
            }}
          >
            Ver2
          </button>
        </div>
        <div style={{ flexGrow: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {renderContent()}
        </div>
      </main>
    </>
  );
}
