import Head from "next/head";
import React, { useState } from 'react';
import Ver1 from '../components/ver1';
import Ver2_1 from '../components/ver2/1';
import Ver2_2 from '../components/ver2/2';
import Ver2_3 from '../components/ver2/3';
import Ver2_4 from '../components/ver2/4';
import Ver2_5 from '../components/ver2/5';
import Ver2_6 from '../components/ver2/6';
import Ver3 from '../components/ver3';
import Ver4 from '../components/ver4';
import Ver5_n1 from '../components/ver5/n1';
import Ver5_n2 from '../components/ver5/n2';
import Ver5_n3 from '../components/ver5/n3';
import Ver5_n4 from '../components/ver5/n4';

export default function Home() {
  const [selectedVersion, setSelectedVersion] = useState(null);
  const [selectedVer2Component, setSelectedVer2Component] = useState(null);
  const [selectedVer5Component, setSelectedVer5Component] = useState(null);

  const renderContent = () => {
    if (selectedVersion === 'ver1') {
      return <Ver1 />;
    } else if (selectedVersion === 'ver2') {
      switch (selectedVer2Component) {
        case 'ver2_1':
          return <Ver2_1 />;
        case 'ver2_2':
          return <Ver2_2 />;
        case 'ver2_3':
          return <Ver2_3 />;
        case 'ver2_4':
          return <Ver2_4 />;
        case 'ver2_5':
          return <Ver2_5 />;
        case 'ver2_6':
          return <Ver2_6 />;
        default:
          return <div>Select a Ver2 component to display.</div>;
      }
    } else if (selectedVersion === 'ver3') {
      return <Ver3 />;
    } else if (selectedVersion === 'ver4') {
      return <Ver4 />;
    } else if (selectedVersion === 'ver5') {
      switch (selectedVer5Component) {
        case 'n1':
          return <Ver5_n1 />;
        case 'n2':
          return <Ver5_n2 />;
        case 'n3':
          return <Ver5_n3 />;
        case 'n4':
          return <Ver5_n4 />;
        default:
          return <div>Select a Ver5 component to display.</div>;
      }
    }
    return <div>Select a version to display.</div>;
  };

  const CircleButton = ({ label, active, onClick }) => (
    <button
      onClick={onClick}
      style={{
        width: 36,
        height: 36,
        borderRadius: '50%',
        border: 'none',
        cursor: 'pointer',
        fontSize: 13,
        backgroundColor: active ? '#0070f3' : '#f0f0f0',
        color: active ? 'white' : 'black',
        boxShadow: '0 2px 6px rgba(0,0,0,0.15)',
        opacity: active ? 0.95 : 0.8
      }}
    >
      {label}
    </button>
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main style={{ display: 'flex', height: '100vh', width: '100vw' }}>
        <div style={{ flexGrow: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
          {renderContent()}
          {/* Floating version buttons attached to interface (top-left) */}
          <div style={{ position: 'absolute', left: 10, top: 10, display: 'flex', flexDirection: 'column', gap: 8, zIndex: 5001 }}>
            <CircleButton label="V1" active={selectedVersion === 'ver1'} onClick={() => { setSelectedVersion('ver1'); setSelectedVer2Component(null); }} />
            <CircleButton label="V2" active={selectedVersion === 'ver2'} onClick={() => { setSelectedVersion('ver2'); setSelectedVer2Component('ver2_1'); }} />
            <CircleButton label="V3" active={selectedVersion === 'ver3'} onClick={() => { setSelectedVersion('ver3'); setSelectedVer2Component(null); }} />
            <CircleButton label="V4" active={selectedVersion === 'ver4'} onClick={() => { setSelectedVersion('ver4'); setSelectedVer2Component(null); }} />
            <CircleButton label="V5" active={selectedVersion === 'ver5'} onClick={() => { setSelectedVersion('ver5'); setSelectedVer2Component(null); setSelectedVer5Component('n1'); }} />
          </div>
          {selectedVersion === 'ver2' && (
            <div style={{ position: 'absolute', top: 6, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 8, zIndex: 5000 }}>
              <CircleButton label="1" active={selectedVer2Component === 'ver2_1'} onClick={() => setSelectedVer2Component('ver2_1')} />
              <CircleButton label="2" active={selectedVer2Component === 'ver2_2'} onClick={() => setSelectedVer2Component('ver2_2')} />
              <CircleButton label="3" active={selectedVer2Component === 'ver2_3'} onClick={() => setSelectedVer2Component('ver2_3')} />
              <CircleButton label="4" active={selectedVer2Component === 'ver2_4'} onClick={() => setSelectedVer2Component('ver2_4')} />
              <CircleButton label="5" active={selectedVer2Component === 'ver2_5'} onClick={() => setSelectedVer2Component('ver2_5')} />
              <CircleButton label="6" active={selectedVer2Component === 'ver2_6'} onClick={() => setSelectedVer2Component('ver2_6')} />
            </div>
          )}
          {selectedVersion === 'ver5' && (
            <div style={{ position: 'absolute', top: 6, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 8, zIndex: 5000 }}>
              <CircleButton label="n1" active={selectedVer5Component === 'n1'} onClick={() => setSelectedVer5Component('n1')} />
              <CircleButton label="n2" active={selectedVer5Component === 'n2'} onClick={() => setSelectedVer5Component('n2')} />
              <CircleButton label="n3" active={selectedVer5Component === 'n3'} onClick={() => setSelectedVer5Component('n3')} />
              <CircleButton label="n4" active={selectedVer5Component === 'n4'} onClick={() => setSelectedVer5Component('n4')} />
            </div>
          )}
        </div>
      </main>
    </>
  );
}
