import Head from "next/head";
import React, { useState } from 'react';
import Ver1 from '../components/ver1';
import Ver5_n1 from '../components/ver5/n1';
import Ver5_n2 from '../components/ver5/n2';
import Ver5_n3 from '../components/ver5/n3';
import Ver5_n4 from '../components/ver5/n4';
import Ver5_n5 from '../components/ver5/n5';
import Ver6_1 from '../components/ver6/1';
import Ver6_1_2 from '../components/ver6/1-2';
import Ver6_2 from '../components/ver6/2';
import Ver6_2_2 from '../components/ver6/2-2';
import Ver6_3 from '../components/ver6/3';
import Ver6_3_2 from '../components/ver6/3-2';

export default function Home() {
  const [selectedVersion, setSelectedVersion] = useState(null);
  const [selectedVer5Component, setSelectedVer5Component] = useState(null);
  const [selectedVer6Component, setSelectedVer6Component] = useState(null);

  const renderContent = () => {
    if (selectedVersion === 'ver1') {
      return <Ver1 />;
    } else if (selectedVersion === 'ver5') {
      switch (selectedVer5Component) {
        case 'n1':
          return <Ver5_n1 />;
        case 'n2':
          return <Ver5_n2 />;
        case 'n3':
          return <Ver5_n3 />;
        case 'n4':
          return <Ver5_n4 />;
        case 'n5':
          return <Ver5_n5 />;
        default:
          return <div>Select a Ver5 component to display.</div>;
      }
    } else if (selectedVersion === 'ver6') {
      switch (selectedVer6Component) {
        case 'ver6_1':
          return <Ver6_1 />;
        case 'ver6_1-2':
          return <Ver6_1_2 />;
        case 'ver6_2':
          return <Ver6_2 />;
        case 'ver6_2-2':
          return <Ver6_2_2 />;
        case 'ver6_3':
          return <Ver6_3 />;
        case 'ver6_3-2':
          return <Ver6_3_2 />;
        default:
          return <div>Select a Ver6 component to display.</div>;
      }
    }
    return <div>Select a version to display.</div>;
  };

  const CircleButton = ({ label, active, onClick }) => (
    <button
      onClick={onClick}
      style={{
        width: 36,
        height: 36,
        borderRadius: '50%',
        border: 'none',
        cursor: 'pointer',
        fontSize: 13,
        backgroundColor: active ? '#0070f3' : '#f0f0f0',
        color: active ? 'white' : 'black',
        boxShadow: '0 2px 6px rgba(0,0,0,0.15)',
        opacity: active ? 0.95 : 0.8
      }}
    >
      {label}
    </button>
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main style={{ display: 'flex', height: '100vh', width: '100vw' }}>
        <div style={{ flexGrow: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
          {renderContent()}
          {/* Floating version buttons attached to interface (top-left) */}
          <div style={{ position: 'absolute', left: 10, top: 10, display: 'flex', flexDirection: 'column', gap: 8, zIndex: 5001 }}>
            <CircleButton label="V1" active={selectedVersion === 'ver1'} onClick={() => { setSelectedVersion('ver1'); setSelectedVer6Component(null); }} />
            <CircleButton label="V5" active={selectedVersion === 'ver5'} onClick={() => { setSelectedVersion('ver5'); setSelectedVer6Component(null); setSelectedVer5Component('n1'); }} />
            <CircleButton label="V6" active={selectedVersion === 'ver6'} onClick={() => { setSelectedVersion('ver6'); setSelectedVer5Component(null); setSelectedVer6Component('ver6_1'); }} />
          </div>
          {selectedVersion === 'ver5' && (
            <div style={{ position: 'absolute', top: 6, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 8, zIndex: 5000 }}>
              <CircleButton label="n1" active={selectedVer5Component === 'n1'} onClick={() => setSelectedVer5Component('n1')} />
              <CircleButton label="n2" active={selectedVer5Component === 'n2'} onClick={() => setSelectedVer5Component('n2')} />
              <CircleButton label="n3" active={selectedVer5Component === 'n3'} onClick={() => setSelectedVer5Component('n3')} />
              <CircleButton label="n4" active={selectedVer5Component === 'n4'} onClick={() => setSelectedVer5Component('n4')} />
              <CircleButton label="n5" active={selectedVer5Component === 'n5'} onClick={() => setSelectedVer5Component('n5')} />
            </div>
          )}
          {selectedVersion === 'ver6' && (
            <div style={{ position: 'absolute', top: 6, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 8, zIndex: 5000 }}>
              <CircleButton label="1" active={selectedVer6Component === 'ver6_1'} onClick={() => setSelectedVer6Component('ver6_1')} />
              <CircleButton label="1-2" active={selectedVer6Component === 'ver6_1-2'} onClick={() => setSelectedVer6Component('ver6_1-2')} />
              <CircleButton label="2" active={selectedVer6Component === 'ver6_2'} onClick={() => setSelectedVer6Component('ver6_2')} />
              <CircleButton label="2-2" active={selectedVer6Component === 'ver6_2-2'} onClick={() => setSelectedVer6Component('ver6_2-2')} />
              <CircleButton label="3" active={selectedVer6Component === 'ver6_3'} onClick={() => setSelectedVer6Component('ver6_3')} />
              <CircleButton label="3-2" active={selectedVer6Component === 'ver6_3-2'} onClick={() => setSelectedVer6Component('ver6_3-2')} />
            </div>
          )}
        </div>
      </main>
    </>
  );
}
